-- MySQL Script generated by MySQL Workbench
-- Wed Dec 13 20:50:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_levents
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_levents
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_levents` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_levents` ;

-- -----------------------------------------------------
-- Table `db_levents`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_levents`.`address` (
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `address_detail` VARCHAR(255) NULL DEFAULT NULL,
  `commune` VARCHAR(255) NULL DEFAULT NULL,
  `district` VARCHAR(255) NULL DEFAULT NULL,
  `province` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 59
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_levents`.`token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_levents`.`token` (
  `create_at` INT NULL DEFAULT NULL,
  `otptoken` INT NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `end_at` DATETIME(6) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_levents`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_levents`.`user` (
  `address_id` BIGINT NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `date_of_birth` DATETIME(6) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `token_id` BIGINT NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `account` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `full_name` VARCHAR(255) NULL DEFAULT NULL,
  `number_phone` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_dhlcfg8h1drrgu0irs1ro3ohb` (`address_id` ASC) VISIBLE,
  UNIQUE INDEX `UK_juv1pmb8agpbeyq3sukru2ys2` (`token_id` ASC) VISIBLE,
  CONSTRAINT `FKddefmvbrws3hvl5t0hnnsv8ox`
    FOREIGN KEY (`address_id`)
    REFERENCES `db_levents`.`address` (`id`),
  CONSTRAINT `FKr7pd8gnabslvvptf7rvb4jij4`
    FOREIGN KEY (`token_id`)
    REFERENCES `db_levents`.`token` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_levents`.`voucher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_levents`.`voucher` (
  `sale_of` DOUBLE NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `end_at` DATETIME(6) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `start_at` DATETIME(6) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9464161475
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_levents`.`bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_levents`.`bill` (
  `into_money` DOUBLE NULL DEFAULT NULL,
  `total_cost` DOUBLE NULL DEFAULT NULL,
  `address_id` BIGINT NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `delivery_date` DATETIME(6) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  `voucher_id` BIGINT NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_41x036mk17suaqwtv5wr73aey` (`address_id` ASC) VISIBLE,
  INDEX `FKqhq5aolak9ku5x5mx11cpjad9` (`user_id` ASC) VISIBLE,
  INDEX `FKsp8lqd3ijs9y7t59djo0y1g1c` (`voucher_id` ASC) VISIBLE,
  CONSTRAINT `FK1f5an6dq4k8u0idf4oxthpf8t`
    FOREIGN KEY (`address_id`)
    REFERENCES `db_levents`.`address` (`id`),
  CONSTRAINT `FKqhq5aolak9ku5x5mx11cpjad9`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_levents`.`user` (`id`),
  CONSTRAINT `FKsp8lqd3ijs9y7t59djo0y1g1c`
    FOREIGN KEY (`voucher_id`)
    REFERENCES `db_levents`.`voucher` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 84
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_levents`.`color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_levents`.`color` (
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `name_color` VARCHAR(255) NULL DEFAULT NULL,
  `statuss` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_levents`.`size`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_levents`.`size` (
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `name_size` VARCHAR(255) NULL DEFAULT NULL,
  `statuss` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_levents`.`custom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_levents`.`custom` (
  `status` BIT(1) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `name_custom` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_levents`.`sale_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_levents`.`sale_product` (
  `sale` DOUBLE NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `end_at` DATETIME(6) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `start_at` DATETIME(6) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_levents`.`thickness`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_levents`.`thickness` (
  `gsm` INT NULL DEFAULT NULL,
  `status` BIT(1) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_levents`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_levents`.`material` (
  `status` BIT(1) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `name_material` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_levents`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_levents`.`product` (
  `product_price` DOUBLE NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `custome_id` BIGINT NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `material_id` BIGINT NULL DEFAULT NULL,
  `sale_id` BIGINT NULL DEFAULT NULL,
  `thickness_id` BIGINT NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `name_product` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `image_type` VARCHAR(255) NULL DEFAULT NULL,
  `image_data` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKb7dfxcsxj92fwx5fgi574283h` (`custome_id` ASC) VISIBLE,
  INDEX `FKw04fq456sc4tk26tnbhvr59o` (`material_id` ASC) VISIBLE,
  INDEX `FKlduwdv4lnd6sstprh61sedod7` (`sale_id` ASC) VISIBLE,
  INDEX `FKn9ubxo2cg60fxa8t6bbigyprm` (`thickness_id` ASC) VISIBLE,
  CONSTRAINT `FKb7dfxcsxj92fwx5fgi574283h`
    FOREIGN KEY (`custome_id`)
    REFERENCES `db_levents`.`custom` (`id`),
  CONSTRAINT `FKlduwdv4lnd6sstprh61sedod7`
    FOREIGN KEY (`sale_id`)
    REFERENCES `db_levents`.`sale_product` (`id`),
  CONSTRAINT `FKn9ubxo2cg60fxa8t6bbigyprm`
    FOREIGN KEY (`thickness_id`)
    REFERENCES `db_levents`.`thickness` (`id`),
  CONSTRAINT `FKw04fq456sc4tk26tnbhvr59o`
    FOREIGN KEY (`material_id`)
    REFERENCES `db_levents`.`material` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 38
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_levents`.`product_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_levents`.`product_detail` (
  `quantity` INT NULL DEFAULT NULL,
  `color_id` BIGINT NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `product_id` BIGINT NULL DEFAULT NULL,
  `size_id` BIGINT NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `image_type` VARCHAR(255) NULL DEFAULT NULL,
  `image_data` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK99vj2np1gk1robp8n6htiweii` (`color_id` ASC) VISIBLE,
  INDEX `FKilxoi77ctyin6jn9robktb16c` (`product_id` ASC) VISIBLE,
  INDEX `FKcum8u2vfvebmmc4xo8de3k35s` (`size_id` ASC) VISIBLE,
  CONSTRAINT `FK99vj2np1gk1robp8n6htiweii`
    FOREIGN KEY (`color_id`)
    REFERENCES `db_levents`.`color` (`id`),
  CONSTRAINT `FKcum8u2vfvebmmc4xo8de3k35s`
    FOREIGN KEY (`size_id`)
    REFERENCES `db_levents`.`size` (`id`),
  CONSTRAINT `FKilxoi77ctyin6jn9robktb16c`
    FOREIGN KEY (`product_id`)
    REFERENCES `db_levents`.`product` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 116
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_levents`.`bill_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_levents`.`bill_detail` (
  `price_now` DOUBLE NULL DEFAULT NULL,
  `bill_id` BIGINT NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `product_detail_id` BIGINT NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `quantity_urchased` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKeolgwyayei3o80bb7rj7t207q` (`bill_id` ASC) VISIBLE,
  INDEX `FK5wgs68xq0wq0ebia10snilq9v` (`product_detail_id` ASC) VISIBLE,
  CONSTRAINT `FK5wgs68xq0wq0ebia10snilq9v`
    FOREIGN KEY (`product_detail_id`)
    REFERENCES `db_levents`.`product_detail` (`id`),
  CONSTRAINT `FKeolgwyayei3o80bb7rj7t207q`
    FOREIGN KEY (`bill_id`)
    REFERENCES `db_levents`.`bill` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 295
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_levents`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_levents`.`category` (
  `status` BIT(1) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `name_category` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_levents`.`exchange_bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_levents`.`exchange_bill` (
  `bill_id` BIGINT NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `describe_reason` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_2h1jkbn3di8oxf43wkkajpb8x` (`bill_id` ASC) VISIBLE,
  CONSTRAINT `FKnf52gngdcf1qa8d2d9w7gnqok`
    FOREIGN KEY (`bill_id`)
    REFERENCES `db_levents`.`bill` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_levents`.`exchange_bill_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_levents`.`exchange_bill_detail` (
  `quantity_of_products_returned` INT NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `ex_change_bill_id` BIGINT NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `product_detail_id` BIGINT NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKt874c0nfvngrfkj5nec8e1kcg` (`ex_change_bill_id` ASC) VISIBLE,
  INDEX `FKi3u4e4rhqjy0re7e0ukl6pma1` (`product_detail_id` ASC) VISIBLE,
  CONSTRAINT `FKi3u4e4rhqjy0re7e0ukl6pma1`
    FOREIGN KEY (`product_detail_id`)
    REFERENCES `db_levents`.`product_detail` (`id`),
  CONSTRAINT `FKt874c0nfvngrfkj5nec8e1kcg`
    FOREIGN KEY (`ex_change_bill_id`)
    REFERENCES `db_levents`.`exchange_bill` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_levents`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_levents`.`image` (
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  `type` VARCHAR(255) NULL DEFAULT NULL,
  `data` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_l8oylel56xvt5huamif0tfhkh` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKlxnnh0ir05khn8iu9tgwh1yyk`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_levents`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_levents`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_levents`.`post` (
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `mo_tdescriptiona` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `image` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_levents`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_levents`.`product_category` (
  `category_id` BIGINT NOT NULL,
  `product_id` BIGINT NOT NULL,
  INDEX `FKkud35ls1d40wpjb5htpp14q4e` (`category_id` ASC) VISIBLE,
  INDEX `FK2k3smhbruedlcrvu6clued06x` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FK2k3smhbruedlcrvu6clued06x`
    FOREIGN KEY (`product_id`)
    REFERENCES `db_levents`.`product` (`id`),
  CONSTRAINT `FKkud35ls1d40wpjb5htpp14q4e`
    FOREIGN KEY (`category_id`)
    REFERENCES `db_levents`.`category` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_levents`.`product_favorite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_levents`.`product_favorite` (
  `status` BIT(1) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_hejtmcimiicx37ivbm26fuawj` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKhyt9336ehun1a1jk0s6rxwei2`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_levents`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_levents`.`product_product_fovorite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_levents`.`product_product_fovorite` (
  `product_favorite_id` BIGINT NOT NULL,
  `product_id` BIGINT NOT NULL,
  INDEX `FKqwu563yni9c39xkpk0akokjv` (`product_favorite_id` ASC) VISIBLE,
  INDEX `FK61s89o11ushvsmrrw6ckjhto2` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FK61s89o11ushvsmrrw6ckjhto2`
    FOREIGN KEY (`product_id`)
    REFERENCES `db_levents`.`product` (`id`),
  CONSTRAINT `FKqwu563yni9c39xkpk0akokjv`
    FOREIGN KEY (`product_favorite_id`)
    REFERENCES `db_levents`.`product_favorite` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_levents`.`return_bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_levents`.`return_bill` (
  `total_cost` DOUBLE NULL DEFAULT NULL,
  `bill_id` BIGINT NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `reason_description` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_rn4ck28t9noa4o66k72hp3snm` (`bill_id` ASC) VISIBLE,
  CONSTRAINT `FKjnx6gpdtot1cktb9dxr9ccffw`
    FOREIGN KEY (`bill_id`)
    REFERENCES `db_levents`.`bill` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 36
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_levents`.`return_bill_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_levents`.`return_bill_detail` (
  `price_at_the_time_of_purchase` DOUBLE NULL DEFAULT NULL,
  `quantity_of_products_returned` INT NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `product_detail_id` BIGINT NULL DEFAULT NULL,
  `return_bill_id` BIGINT NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK5ri8myffr09sgx19y8vbxmra0` (`product_detail_id` ASC) VISIBLE,
  INDEX `FKepsscnny4oge3j3dt9i4v2u5y` (`return_bill_id` ASC) VISIBLE,
  CONSTRAINT `FK5ri8myffr09sgx19y8vbxmra0`
    FOREIGN KEY (`product_detail_id`)
    REFERENCES `db_levents`.`product_detail` (`id`),
  CONSTRAINT `FKepsscnny4oge3j3dt9i4v2u5y`
    FOREIGN KEY (`return_bill_id`)
    REFERENCES `db_levents`.`return_bill` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 58
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_levents`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_levents`.`role` (
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `role_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_levents`.`work_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_levents`.`work_schedule` (
  `end_at` TIME NULL DEFAULT NULL,
  `start_at` TIME NULL DEFAULT NULL,
  `status` BIT(1) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `name_work_schedule` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_levents`.`shift_assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_levents`.`shift_assignment` (
  `final_amount` DOUBLE NULL DEFAULT NULL,
  `starting_amount` DOUBLE NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `end_at` DATETIME(6) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `start_at` DATETIME(6) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  `work_schedules_id` BIGINT NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKhkpbn7bbtylosp8k4eoiccuj7` (`user_id` ASC) VISIBLE,
  INDEX `FKt86x4sj6xpucned96l3gw55w5` (`work_schedules_id` ASC) VISIBLE,
  CONSTRAINT `FKhkpbn7bbtylosp8k4eoiccuj7`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_levents`.`user` (`id`),
  CONSTRAINT `FKt86x4sj6xpucned96l3gw55w5`
    FOREIGN KEY (`work_schedules_id`)
    REFERENCES `db_levents`.`work_schedule` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_levents`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_levents`.`user_role` (
  `role_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  INDEX `FKa68196081fvovjhkek5m97n3y` (`role_id` ASC) VISIBLE,
  INDEX `FK859n2jvi8ivhui0rl0esws6o` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK859n2jvi8ivhui0rl0esws6o`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_levents`.`user` (`id`),
  CONSTRAINT `FKa68196081fvovjhkek5m97n3y`
    FOREIGN KEY (`role_id`)
    REFERENCES `db_levents`.`role` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_levents`.`user_voucher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_levents`.`user_voucher` (
  `user_id` BIGINT NOT NULL,
  `voucher_id` BIGINT NOT NULL,
  INDEX `FK98wtp768dsh1cjpuiqbnphb7a` (`user_id` ASC) VISIBLE,
  INDEX `FK5llb4x2ixiwa75csgei7hbl5r` (`voucher_id` ASC) VISIBLE,
  CONSTRAINT `FK5llb4x2ixiwa75csgei7hbl5r`
    FOREIGN KEY (`voucher_id`)
    REFERENCES `db_levents`.`voucher` (`id`),
  CONSTRAINT `FK98wtp768dsh1cjpuiqbnphb7a`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_levents`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `db_levents` ;

-- -----------------------------------------------------
-- procedure update_voucher_status
-- -----------------------------------------------------

DELIMITER $$
USE `db_levents`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `update_voucher_status`()
BEGIN
	SET SQL_SAFE_UPDATES = 0;
    UPDATE db_levents.voucher
    SET status =
        CASE
            WHEN NOW(6) BETWEEN start_at AND end_at THEN '1'
            ELSE '2'
        END;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
